### ISSUE TITLE
Comware V7, unknown-element Bad Element: LacpEdgeEnable

### ISSUE THREAD

**Issue by webminster** [HPENetworking/pyhpecw7#2]
I executed the code sequence below, to try to list portchannels on an HPE A5820AF-24XG Switch:
HP Comware Software, Version 7.1.045, Release 7006P15

from pyhpecw7.comware import HPCOM7
from pyhpecw7.features.portchannel import Portchannel
client = HPCOM7(host="10.12.2.x", username='x', password='z')
pc = Portchannel(client, "1", "bridged")
pc.get_portchannels()

Threw a traceback.   Am I misunderstanding usage of the module, or is there a bug?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyhpecw7/features/portchannel.py", line 114, in get_portchannels
    nc_get_reply = self.device.get(('subtree', top))
  File "pyhpecw7/comware.py", line 320, in get
    rsp = self.execute(self.connection.get, [get_tuple])
  File "pyhpecw7/comware.py", line 210, in execute
    raise NCError(e)
pyhpecw7.errors.NCError: NCError: NETCONF Protocol error (Unexpected element 'http://www.hp.com/netconf/data:1.0':'LacpEdgeEnable' under element '/rpc/get[1]/filter[1]/top[1]/LAGG[1]/LAGGGroups[1]/LAGGGroup[1]). Tag: unknown-element Bad Element: LacpEdgeEnable

**Comment by JeffKabel** [comment]
The current release of Comware v7 on the 58xx series has not been tested yet with these modules.  We are working on a new train release that will be based on the current branch that these scripts were written against.  Give us some time to see if we can resolve this issue or determine if this will be resolved with the next release.
