### ISSUE TITLE
Don't support 20G interface of 6127XLG

### ISSUE THREAD

**Issue by zhangshilinh3c** [HPENetworking/pyhpecw7#3]
Don't support 20G interface of 6127XLG.
Could you do the following modification in pyhpecw7\features\interface.py file?
        self._iface_types = set(['FortyGigE', 'Tunnel', 'LoopBack',
                                 'Vlan-interface', 'Bridge-Aggregation',
                                 'Route-Aggregation', 'GigabitEthernet',
                                 **'TwentyGigE',** 'Ten-GigabitEthernet'])
        elif if_name.lower().startswith('tu'):
            if_type = 'Tunnel'
        **elif if_name.lower().startswith('tw'):
            if_type = 'TwentyGigE'**
        else:

        if not self.iface_exists:
            if self.iface_type in {'FortyGigE', 'GigabitEthernet',
                                   **'TwentyGigE',** 'Ten-GigabitEthernet'}:
                raise InterfaceAbsentError(self.interface_name)

**Comment by JeffKabel** [comment]
Thank you for providing the fix.
