### ISSUE TITLE
Tag: unknown-element Bad Element: Inventory

### ISSUE THREAD

**Issue by aduitsis** [HPENetworking/pyhpecw7#7]
Similar to the other already open issue, when trying to

`facts=Facts(device).get_facts()`, 

I get

`pyhpecw7.errors.NCError: NCError: NETCONF Protocol error (Unexpected element 'http://www.hp.com/netconf/data:1.0':'Inventory' under element '/rpc/get[1]/filter[1]/top[1]/LLDP[1]). Tag: unknown-element Bad Element: Inventory`

when testing against 7.1.045, Release 2311P05.

**Comment by Judymengying** [comment]
This version does not support 'Inventory' element .

**Comment by netmanchris** [comment]
This version does not support 'Inventory' element .
